version: '3.1'

services:

  db:
    image: postgres

    restart: always
    environment:
      POSTGRES_DB: surfing_blog
      POSTGRES_USER: surfing
      POSTGRES_PASSWORD: surfing
      PGDATA: /ver/lib/postgresql/data/pgdata

    ports:
      - "5436:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
#то что не должно стираться при удаления контейнера
volumes:
  db-data: